<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <AvaloniaVersion>TEMPLATE_AVALONIA_VERSION</AvaloniaVersion>
    </PropertyGroup>

    <ItemGroup>
        <!-- Avalonia packages -->
        <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
        <!-- Evergine graphics backends (Windows implementation) -->
        <PackageReference Include="Evergine.DirectX11" Version="TEMPLATE_EVERGINE_VERSION" />
        <PackageReference Include="Evergine.HLSLEverywhere" Version="TEMPLATE_EVERGINE_VERSION" />
        <PackageReference Include="Evergine.Avalonia" Version="TEMPLATE_EVERGINE_VERSION" />
        <PackageReference Include="Evergine.Targets" Version="TEMPLATE_EVERGINE_VERSION" />
        <PackageReference Include="Evergine.Targets.Avalonia" Version="TEMPLATE_EVERGINE_VERSION" />
        <!-- Evergine audio backend (Windows implementation) -->
        <PackageReference Include="Evergine.XAudio2" Version="TEMPLATE_EVERGINE_VERSION" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\AvaGine\AvaGine.csproj"/>
    </ItemGroup>
</Project>
